 def get_random_coffee_reading(self):
        """Generate a random reading from a curated set of fresh funny and motivational quotes."""
        quotes = [
            # Fresh funny quotes
            "Your code works on Fridays but sulks on Mondays",
            "Rubber duck debugging: now with actual quacking",
            "Stack Overflow saved my marriage and my sanity",
            "Git blame: the most honest feature ever invented",
            "My programs have trust issues with semicolons",
            "404 motivation not found, try again after coffee",
            "Debugging is like being a detective in a crime you committed",
            "I speak fluent sarcasm and broken JavaScript",
            "Error messages are just computers having feelings",
            "My code is like my jokes: only I understand them",
            "Programmer's diet: coffee, pizza, and existential dread",
            "I don't always test my code, but when I do, I do it in production",
            "Comments in code are like promises: mostly lies",
            "My favorite programming language is Google",
            "Real programmers count from zero, including their problems",
            "Ctrl+Z is the closest thing we have to time travel",
            "Bug or feature? Depends on who's asking",
            "I'm not procrastinating, I'm doing background processing",
            "Code review is just fancy bullying with syntax highlighting",
            "My rubber duck has better problem-solving skills than me",
            "Programming is 10% writing code, 90% wondering why it doesn't work",
            "I have 99 problems but a glitch ain't one, oh wait",
            "Machine learning: teaching computers to be wrong with confidence",
            "My code is like fine wine: it gets better with age and makes me dizzy",
            "Recursion: see recursion",
            "There are only two hard things in programming: naming things and cache invalidation",
            "Git commit messages: where honesty goes to die",
            "My programming superpower is turning coffee into bugs",
            "Code refactoring: making the same mistake more elegantly",
            "I'm not lazy, I'm just in energy saving mode",
            
            # Fresh motivational quotes
            "Every expert was once a disaster with WiFi",
            "Your potential is loading, please be patient",
            "Greatness is just stubbornness with better PR",
            "Progress is the compound interest of tiny improvements",
            "Your comfort zone called, it's worried about you",
            "Failure is just success taking the scenic route",
            "You're not behind, you're on your own timeline",
            "Dreams don't expire, they just need better project management",
            "Perfectionism is procrastination wearing a fancy hat",
            "Your future self is secretly rooting for you",
            "Consistency is boring until it's legendary",
            "Small steps can take you surprisingly far places",
            "You're allowed to change your mind and your code",
            "Growth happens in the gap between comfort and panic",
            "Your mistakes are just unreleased features",
            "Confidence is a choice, not a feeling",
            "You're exactly where you need to be to get where you're going",
            "Excellence is a habit disguised as talent",
            "Your weird ideas might be exactly what the world needs",
            "Rest is not a reward for work done, it's fuel for work ahead",
            "You don't need permission to be brilliant",
            "Every master was once a beginner who refused to give up",
            "Your pace is perfect for your journey",
            "Momentum builds quietly then arrives suddenly",
            "You're capable of more than you remember",
            "Progress looks different for everyone, including you",
            "Your story is still being written, so make it interesting",
            "Comparison is the thief of joy and productivity",
            "You're learning even when it doesn't feel like it",
            "Every day you don't quit is a victory worth celebrating",
            
            # Longer motivational passages
            "The gap between where you are and where you want to be isn't filled with perfect plans—it's filled with messy action, kind patience with yourself, and the faith that effort compounds even when you can't see it happening.",
            "You don't need to see the whole staircase to take the first step, and you don't need to understand the entire system to improve one small part of it—progress is permission enough to keep going.",
            "Your brain will convince you that starting is the hardest part, but the secret is that continuing is where the real magic happens—show up tomorrow even when today felt like a beautiful disaster.",
            "The work you're avoiding probably holds the key to everything else getting easier, and the solution you need is probably simpler than the problem you're creating by not starting.",
            "Every person you admire started exactly where you are now: confused, eager, and making it up as they went along—the only difference is they kept going when it felt impossible.",
            "You're not behind schedule; you're exactly on time for your own life, which moves at the speed of learning, not the speed of comparison to others.",
            "Your creativity thrives on constraints, your productivity loves routines, and your happiness grows when you stop asking permission to take up space in your own story.",
            "The hardest part about building something meaningful isn't the technical challenges—it's trusting that your taste, effort, and willingness to iterate will eventually converge into something worth sharing.",
            "You already have everything you need to start: curiosity about what's possible, access to information, and the ability to try things badly until you learn to do them well.",
            "The version of you that solves this problem is already inside you, waiting patiently for you to stop overthinking and start experimenting with what might work instead of worrying about what might not."
        ]
        
        import random
        return random.choice(quotes)
